// Catalogo esercizi diario-coach v2 — Wave 2.1
// Owner: kb-content-specialist
//
// Format e contract definiti in ARCHITECTURE.md §2.1 (Exercise type).
// Lookup O(1) via EXERCISES_BY_ID. Tutti gli ID sono slug kebab-case stabili
// (NON rinominare senza migration: persistiti in workout.exercises[].exerciseId).
//
// Coverage attesa (verificata in __tests__/exercises.test.ts):
//   squat ≥10 · hinge ≥10 · lunge ≥6 · horizontal_push ≥10 · vertical_push ≥8
//   horizontal_pull ≥8 · vertical_pull ≥6 · carry ≥3 · core_antiext ≥4
//   core_antirot ≥4 · plyometric ≥4 · sport-specific calcio ≥3 · TOTAL ≥80.
//
// NOTA import: `Exercise` viene da `../types/exercise.ts` creato dallo
// Schema Specialist in parallelo (Wave 2.1). Se al momento del checkout il file
// non esiste ancora, vedi il fallback inline `interface Exercise` in fondo.
// Una volta che Schema completa, rimuovere il fallback e tenere solo l'import.

import type { Exercise } from "../types/exercise";

export const EXERCISES: Exercise[] = [
  // ===========================================================================
  // PATTERN: SQUAT (12 esercizi)
  // ===========================================================================
  {
    id: "back-squat-barbell",
    name: "Back Squat con bilanciere",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["adduttori", "core", "lombari"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Petto alto, ginocchia in linea con piedi, schiena neutra. Discesa controllata sotto parallelo se mobilità lo consente.",
    cautions: ["lombare ernia", "ginocchio acuto"],
    alternatives: ["goblet-squat-kettlebell", "front-squat-barbell", "hack-squat-machine", "leg-press-machine"],
    loadable: true,
  },
  {
    id: "front-squat-barbell",
    name: "Front Squat con bilanciere",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core", "trapezio", "deltoidi anteriori"],
    equipment: ["barbell"],
    level: "advanced",
    unilateral: false,
    technique: "Bilanciere su deltoidi anteriori, gomiti alti. Busto più verticale che back squat, riduce stress lombare.",
    cautions: ["lombare ernia", "polso rigido"],
    alternatives: ["goblet-squat-kettlebell", "back-squat-barbell", "zercher-squat-barbell"],
    loadable: true,
  },
  {
    id: "goblet-squat-kettlebell",
    name: "Goblet Squat con kettlebell",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core", "adduttori"],
    equipment: ["kettlebell"],
    level: "beginner",
    unilateral: false,
    technique: "Kettlebell tenuto al petto a due mani, gomiti dentro. Discesa profonda con busto verticale, tallone a terra.",
    alternatives: ["back-squat-barbell", "bodyweight-squat", "dumbbell-squat"],
    loadable: true,
  },
  {
    id: "dumbbell-squat",
    name: "Squat con manubri",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["adduttori", "core"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Manubri lungo i fianchi o sulle spalle. Discesa sotto parallelo, ginocchia in linea con piedi.",
    alternatives: ["goblet-squat-kettlebell", "back-squat-barbell", "bodyweight-squat"],
    loadable: true,
  },
  {
    id: "bulgarian-split-squat-dumbbell",
    name: "Bulgarian Split Squat con manubri",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["adduttori", "core", "stabilizzatori anca"],
    equipment: ["dumbbell", "bench"],
    level: "intermediate",
    unilateral: true,
    technique: "Piede posteriore elevato 20-30cm, busto leggermente in avanti. Discesa controllata, ginocchio anteriore non oltre la punta in modo eccessivo.",
    cautions: ["ginocchio acuto"],
    alternatives: ["bulgarian-split-squat-bodyweight", "forward-lunge-dumbbell", "step-up-dumbbell"],
    loadable: true,
  },
  {
    id: "bulgarian-split-squat-bodyweight",
    name: "Bulgarian Split Squat a corpo libero",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["adduttori", "core"],
    equipment: ["bodyweight", "bench"],
    level: "beginner",
    unilateral: true,
    technique: "Mani sui fianchi o pregando. Piede posteriore su panca/divano. Discesa lenta 2-3 secondi.",
    alternatives: ["bulgarian-split-squat-dumbbell", "forward-lunge-bodyweight", "bodyweight-squat"],
    loadable: false,
  },
  {
    id: "pistol-squat-bodyweight",
    name: "Pistol Squat",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core", "stabilizzatori anca", "polpaccio"],
    equipment: ["bodyweight"],
    level: "advanced",
    unilateral: true,
    technique: "Squat su una gamba con altra estesa avanti. Braccia avanti per contrappeso. Richiede mobilità caviglia + forza monopodalica.",
    cautions: ["ginocchio acuto"],
    alternatives: ["bulgarian-split-squat-bodyweight", "step-up-dumbbell", "single-leg-box-squat"],
    loadable: false,
  },
  {
    id: "jump-squat-bodyweight",
    name: "Jump Squat",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["polpaccio", "core"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: false,
    technique: "Squat parallelo, esplosione verticale, atterraggio morbido sulla pianta del piede. Pause tra rep per qualità.",
    cautions: ["ginocchio acuto", "polpaccio acuto"],
    alternatives: ["box-jump", "broad-jump", "bodyweight-squat"],
    loadable: false,
  },
  {
    id: "box-squat-barbell",
    name: "Box Squat con bilanciere",
    pattern: "squat",
    primaryMuscles: ["glutei", "quadricipiti"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["barbell", "box"],
    level: "intermediate",
    unilateral: false,
    technique: "Discesa controllata fino a sfiorare/sedersi su box, breve pausa, esplosione concentrica. Insegna profondità coerente.",
    alternatives: ["back-squat-barbell", "front-squat-barbell", "goblet-squat-kettlebell"],
    loadable: true,
  },
  {
    id: "hack-squat-machine",
    name: "Hack Squat alla macchina",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["adduttori"],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Schiena appoggiata al pad, piedi a metà piattaforma. Discesa controllata 90° ginocchio. Riduce stress lombare vs squat libero.",
    alternatives: ["leg-press-machine", "back-squat-barbell", "goblet-squat-kettlebell"],
    loadable: true,
  },
  {
    id: "leg-press-machine",
    name: "Leg Press alla macchina",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["adduttori", "femorali"],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Piedi a larghezza spalle a metà piattaforma. Range 90° ginocchio o leggermente sotto. Schiena bassa aderente.",
    alternatives: ["hack-squat-machine", "back-squat-barbell", "goblet-squat-kettlebell"],
    loadable: true,
  },
  {
    id: "bodyweight-squat",
    name: "Squat a corpo libero",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Piedi a larghezza spalle, braccia avanti per contrappeso. Discesa sotto parallelo se mobilità lo permette.",
    alternatives: ["goblet-squat-kettlebell", "dumbbell-squat", "wall-sit"],
    loadable: false,
  },
  {
    id: "wall-sit",
    name: "Wall Sit (squat isometrico)",
    pattern: "isometric",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Schiena al muro, ginocchia 90°, cosce parallele al pavimento. Mantenere 30-60s.",
    alternatives: ["bodyweight-squat", "goblet-squat-kettlebell"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: HINGE (10 esercizi)
  // ===========================================================================
  {
    id: "deadlift-conventional-barbell",
    name: "Stacco da terra convenzionale",
    pattern: "hinge",
    primaryMuscles: ["femorali", "glutei", "lombari"],
    secondaryMuscles: ["dorsali", "trapezio", "core", "quadricipiti"],
    equipment: ["barbell"],
    level: "advanced",
    unilateral: false,
    technique: "Bilanciere sopra metà piede, presa larghezza spalle, schiena neutra dall'inizio. Spinta gambe + estensione anca simultanee.",
    cautions: ["lombare ernia", "discopatia attiva"],
    alternatives: ["deadlift-romanian-barbell", "deadlift-sumo-barbell", "trap-bar-deadlift", "kettlebell-swing"],
    loadable: true,
  },
  {
    id: "deadlift-sumo-barbell",
    name: "Stacco sumo con bilanciere",
    pattern: "hinge",
    primaryMuscles: ["glutei", "adduttori", "femorali"],
    secondaryMuscles: ["quadricipiti", "trapezio", "core"],
    equipment: ["barbell"],
    level: "advanced",
    unilateral: false,
    technique: "Stance largo (oltre spalle), punte aperte 30-45°, presa interna alle gambe. Range più corto vs convenzionale, busto più verticale.",
    cautions: ["lombare ernia", "anca rigida"],
    alternatives: ["deadlift-conventional-barbell", "deadlift-romanian-barbell", "kettlebell-swing"],
    loadable: true,
  },
  {
    id: "deadlift-romanian-barbell",
    name: "Stacco rumeno (RDL) con bilanciere",
    pattern: "hinge",
    primaryMuscles: ["femorali", "glutei"],
    secondaryMuscles: ["lombari", "core"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Ginocchia leggermente piegate, hip hinge spostando bacino indietro. Discesa fino tibie con bilanciere vicino. Schiena neutra.",
    cautions: ["lombare acuto", "femorale strain recente"],
    alternatives: ["deadlift-romanian-dumbbell", "good-morning-barbell", "kettlebell-swing", "single-leg-rdl-dumbbell"],
    loadable: true,
  },
  {
    id: "deadlift-romanian-dumbbell",
    name: "Stacco rumeno con manubri",
    pattern: "hinge",
    primaryMuscles: ["femorali", "glutei"],
    secondaryMuscles: ["lombari", "core"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Manubri davanti alle cosce, hip hinge controllato. Versione più accessibile vs barbell per home gym.",
    cautions: ["lombare acuto"],
    alternatives: ["deadlift-romanian-barbell", "single-leg-rdl-dumbbell", "kettlebell-swing"],
    loadable: true,
  },
  {
    id: "single-leg-rdl-dumbbell",
    name: "Stacco rumeno monopodalico con manubri",
    pattern: "hinge",
    primaryMuscles: ["femorali", "glutei"],
    secondaryMuscles: ["core", "stabilizzatori anca", "lombari"],
    equipment: ["dumbbell"],
    level: "intermediate",
    unilateral: true,
    technique: "Manubrio nella mano opposta alla gamba di appoggio. Hip hinge mantenendo allineamento spalla-anca-tallone in linea.",
    alternatives: ["deadlift-romanian-dumbbell", "kickback-glute-band", "good-morning-barbell"],
    loadable: true,
  },
  {
    id: "trap-bar-deadlift",
    name: "Stacco con trap bar",
    pattern: "hinge",
    primaryMuscles: ["femorali", "glutei", "quadricipiti"],
    secondaryMuscles: ["trapezio", "core"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Posizionarsi al centro della trap bar, presa neutra. Riduce stress lombare vs convenzionale, più simile a uno squat-deadlift ibrido.",
    cautions: ["lombare cronico"],
    alternatives: ["deadlift-conventional-barbell", "deadlift-romanian-barbell", "goblet-squat-kettlebell"],
    loadable: true,
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing (Russian)",
    pattern: "hinge",
    primaryMuscles: ["glutei", "femorali"],
    secondaryMuscles: ["core", "spalle", "lombari"],
    equipment: ["kettlebell"],
    level: "intermediate",
    unilateral: false,
    technique: "Hip hinge esplosivo. Kettlebell oscilla per momentum dell'anca, NON per sollevamento di braccio. Endpoint altezza spalle (russian) o overhead (american).",
    cautions: ["lombare acuto"],
    alternatives: ["deadlift-romanian-dumbbell", "hip-thrust-barbell", "good-morning-barbell"],
    loadable: true,
  },
  {
    id: "good-morning-barbell",
    name: "Good Morning con bilanciere",
    pattern: "hinge",
    primaryMuscles: ["femorali", "glutei", "lombari"],
    secondaryMuscles: ["core"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Bilanciere sui trapezi alti, hip hinge mantenendo curva lombare. Carico moderato, focus sulla tecnica.",
    cautions: ["lombare ernia", "discopatia"],
    alternatives: ["deadlift-romanian-barbell", "kettlebell-swing", "single-leg-rdl-dumbbell"],
    loadable: true,
  },
  {
    id: "hip-thrust-barbell",
    name: "Hip Thrust con bilanciere",
    pattern: "hinge",
    primaryMuscles: ["glutei"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["barbell", "bench"],
    level: "intermediate",
    unilateral: false,
    technique: "Schiena alta su panca, bilanciere sopra le anche (con pad). Spinta verso l'alto a glutei, mento verso lo sterno top position.",
    alternatives: ["glute-bridge-bodyweight", "kickback-glute-band", "kettlebell-swing"],
    loadable: true,
  },
  {
    id: "glute-bridge-bodyweight",
    name: "Glute Bridge a terra",
    pattern: "hinge",
    primaryMuscles: ["glutei"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Schiena a terra, ginocchia piegate, talloni vicino ai glutei. Spinta verticale fino allineamento anca-ginocchio-spalla.",
    alternatives: ["hip-thrust-barbell", "single-leg-glute-bridge", "kettlebell-swing"],
    loadable: false,
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    pattern: "hinge",
    primaryMuscles: ["glutei"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: true,
    technique: "Una gamba estesa avanti, spinta verticale sull'altro tallone. Controllo isometrico al top per 1-2s.",
    alternatives: ["glute-bridge-bodyweight", "hip-thrust-barbell", "single-leg-rdl-dumbbell"],
    loadable: false,
  },
  {
    id: "kickback-glute-band",
    name: "Kickback gluteo con elastico",
    pattern: "hinge",
    primaryMuscles: ["glutei"],
    secondaryMuscles: ["lombari"],
    equipment: ["band"],
    level: "beginner",
    unilateral: true,
    technique: "Elastico ad anca o caviglia. Estensione anca controllata mantenendo bacino neutro. Range corto, contrazione lenta.",
    alternatives: ["single-leg-glute-bridge", "hip-thrust-barbell", "single-leg-rdl-dumbbell"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: LUNGE (7 esercizi)
  // ===========================================================================
  {
    id: "forward-lunge-dumbbell",
    name: "Affondo frontale con manubri",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["femorali", "core", "stabilizzatori anca"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: true,
    technique: "Passo avanti, discesa fino ginocchio posteriore vicino al suolo. Spinta sul tallone anteriore per tornare.",
    cautions: ["ginocchio acuto"],
    alternatives: ["forward-lunge-bodyweight", "reverse-lunge-dumbbell", "walking-lunge-dumbbell"],
    loadable: true,
  },
  {
    id: "forward-lunge-bodyweight",
    name: "Affondo frontale a corpo libero",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Mani sui fianchi. Step avanti, discesa controllata, push back con tallone anteriore.",
    alternatives: ["reverse-lunge-bodyweight", "forward-lunge-dumbbell", "bulgarian-split-squat-bodyweight"],
    loadable: false,
  },
  {
    id: "reverse-lunge-dumbbell",
    name: "Affondo posteriore con manubri",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: true,
    technique: "Passo indietro invece che avanti. Più gentile su ginocchio anteriore vs forward lunge.",
    alternatives: ["forward-lunge-dumbbell", "walking-lunge-dumbbell", "step-up-dumbbell"],
    loadable: true,
  },
  {
    id: "reverse-lunge-bodyweight",
    name: "Affondo posteriore a corpo libero",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Mani sui fianchi, step indietro. Più stabile per principianti.",
    alternatives: ["forward-lunge-bodyweight", "reverse-lunge-dumbbell", "bulgarian-split-squat-bodyweight"],
    loadable: false,
  },
  {
    id: "walking-lunge-dumbbell",
    name: "Affondi camminati con manubri",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["femorali", "core", "stabilizzatori"],
    equipment: ["dumbbell"],
    level: "intermediate",
    unilateral: true,
    technique: "Affondi alternati avanzando. Stimolo continuo, demand cardiovascolare aggiunta.",
    alternatives: ["forward-lunge-dumbbell", "reverse-lunge-dumbbell", "bulgarian-split-squat-dumbbell"],
    loadable: true,
  },
  {
    id: "lateral-lunge-dumbbell",
    name: "Affondo laterale con manubri",
    pattern: "lunge",
    primaryMuscles: ["adduttori", "glutei", "quadricipiti"],
    secondaryMuscles: ["core"],
    equipment: ["dumbbell"],
    level: "intermediate",
    unilateral: true,
    technique: "Step laterale ampio, peso sulla gamba di affondo, altra estesa. Mobilità anca + stretch attivo adduttori.",
    cautions: ["adduttore strain"],
    alternatives: ["forward-lunge-dumbbell", "cossack-squat-bodyweight", "step-up-dumbbell"],
    loadable: true,
  },
  {
    id: "jumping-lunge-bodyweight",
    name: "Jumping Lunge",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["polpaccio", "core"],
    equipment: ["bodyweight"],
    level: "advanced",
    unilateral: true,
    technique: "Affondo, salto verticale con cambio gamba in aria, atterraggio in affondo opposto. Atterraggio morbido.",
    cautions: ["ginocchio acuto", "polpaccio recente"],
    alternatives: ["jump-squat-bodyweight", "box-jump", "forward-lunge-bodyweight"],
    loadable: false,
  },
  {
    id: "step-up-dumbbell",
    name: "Step-Up con manubri",
    pattern: "lunge",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["femorali", "core", "polpaccio"],
    equipment: ["dumbbell", "box"],
    level: "beginner",
    unilateral: true,
    technique: "Box altezza ginocchio. Salire spingendo con tallone, NO usare slancio della gamba bassa. Discesa controllata.",
    alternatives: ["bulgarian-split-squat-dumbbell", "reverse-lunge-dumbbell", "forward-lunge-dumbbell"],
    loadable: true,
  },
  {
    id: "cossack-squat-bodyweight",
    name: "Cossack Squat",
    pattern: "lunge",
    primaryMuscles: ["adduttori", "quadricipiti", "glutei"],
    secondaryMuscles: ["core", "stabilizzatori anca"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: true,
    technique: "Stance largo, peso lateralmente su una gamba flettendola, altra estesa con tallone a terra. Mobilità + forza unilaterale.",
    alternatives: ["lateral-lunge-dumbbell", "bulgarian-split-squat-bodyweight", "pistol-squat-bodyweight"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: HORIZONTAL_PUSH (10 esercizi)
  // ===========================================================================
  {
    id: "bench-press-flat-barbell",
    name: "Panca piana con bilanciere",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti", "deltoidi anteriori"],
    secondaryMuscles: ["core"],
    equipment: ["barbell", "bench"],
    level: "intermediate",
    unilateral: false,
    technique: "Scapole retratte e depresse. Bar al petto controllata, gomiti ~75° vs torso. Spinta esplosiva, polsi neutri.",
    cautions: ["spalla acuta"],
    alternatives: ["bench-press-dumbbell", "push-up-standard", "bench-press-machine"],
    loadable: true,
  },
  {
    id: "bench-press-incline-barbell",
    name: "Panca inclinata con bilanciere",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali alti", "deltoidi anteriori", "tricipiti"],
    secondaryMuscles: ["core"],
    equipment: ["barbell", "bench"],
    level: "intermediate",
    unilateral: false,
    technique: "Inclinazione 30-45°. Stimolo maggiore su pettorale superiore. Toccare clavicole/petto alto, NON gola.",
    alternatives: ["bench-press-incline-dumbbell", "bench-press-flat-barbell", "push-up-decline"],
    loadable: true,
  },
  {
    id: "bench-press-incline-dumbbell",
    name: "Panca inclinata con manubri",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali alti", "deltoidi anteriori", "tricipiti"],
    secondaryMuscles: ["core", "stabilizzatori spalla"],
    equipment: ["dumbbell", "bench"],
    level: "intermediate",
    unilateral: false,
    technique: "ROM più ampio vs barbell. Manubri si toccano top o quasi. Discesa controllata fino linea pettorale.",
    alternatives: ["bench-press-incline-barbell", "bench-press-dumbbell", "push-up-decline"],
    loadable: true,
  },
  {
    id: "bench-press-dumbbell",
    name: "Panca piana con manubri",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti", "deltoidi anteriori"],
    secondaryMuscles: ["core", "stabilizzatori spalla"],
    equipment: ["dumbbell", "bench"],
    level: "beginner",
    unilateral: false,
    technique: "Manubri allineati con linea pettorale. ROM più ampio + meno stress spalla vs barbell. Buona alternativa home gym.",
    alternatives: ["bench-press-flat-barbell", "push-up-standard", "bench-press-machine"],
    loadable: true,
  },
  {
    id: "push-up-standard",
    name: "Push-up classici",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti", "deltoidi anteriori"],
    secondaryMuscles: ["core", "serrato anteriore"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Mani larghezza spalle, corpo in plank rigido (no anche cadenti). Discesa controllata fino petto vicino al suolo.",
    alternatives: ["push-up-knees", "push-up-decline", "bench-press-dumbbell"],
    loadable: false,
  },
  {
    id: "push-up-knees",
    name: "Push-up sulle ginocchia",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti", "deltoidi anteriori"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Versione regression. Linea retta ginocchio-anca-spalla. Adatto a inizio o per volume su rep alte.",
    alternatives: ["push-up-standard", "push-up-incline", "wall-push-up"],
    loadable: false,
  },
  {
    id: "push-up-decline",
    name: "Push-up declinati (piedi su rialzo)",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali alti", "deltoidi anteriori", "tricipiti"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight", "box"],
    level: "intermediate",
    unilateral: false,
    technique: "Piedi su panca o box. Stimolo più alto vs standard, simula incline bench.",
    alternatives: ["push-up-standard", "bench-press-incline-dumbbell", "pike-push-up"],
    loadable: false,
  },
  {
    id: "push-up-incline",
    name: "Push-up inclinati (mani su rialzo)",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti"],
    secondaryMuscles: ["deltoidi", "core"],
    equipment: ["bodyweight", "box"],
    level: "beginner",
    unilateral: false,
    technique: "Mani su panca o box. Regression intermedia tra knee push-up e standard.",
    alternatives: ["push-up-standard", "push-up-knees", "wall-push-up"],
    loadable: false,
  },
  {
    id: "wall-push-up",
    name: "Push-up al muro",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti", "deltoidi"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Mani al muro larghezza spalle. Versione massima regression per principianti totali o riabilitazione.",
    alternatives: ["push-up-knees", "push-up-incline", "push-up-standard"],
    loadable: false,
  },
  {
    id: "dips-parallel-bars",
    name: "Dips alle parallele",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali bassi", "tricipiti", "deltoidi anteriori"],
    secondaryMuscles: ["core", "trapezio"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: false,
    technique: "Busto leggermente in avanti per pectoral focus, dritto per tricipiti. Discesa fino spalle = gomiti, NO sotto.",
    cautions: ["spalla acuta"],
    alternatives: ["bench-dips", "push-up-decline", "bench-press-flat-barbell"],
    loadable: false,
  },
  {
    id: "bench-dips",
    name: "Dips alla panca",
    pattern: "horizontal_push",
    primaryMuscles: ["tricipiti", "pettorali"],
    secondaryMuscles: ["deltoidi anteriori"],
    equipment: ["bodyweight", "bench"],
    level: "beginner",
    unilateral: false,
    technique: "Mani su panca dietro la schiena, gambe estese o piegate. Discesa controllata 90° gomito.",
    cautions: ["spalla acuta"],
    alternatives: ["dips-parallel-bars", "push-up-standard", "tricep-extension-dumbbell"],
    loadable: false,
  },
  {
    id: "bench-press-machine",
    name: "Chest Press alla macchina",
    pattern: "horizontal_push",
    primaryMuscles: ["pettorali", "tricipiti", "deltoidi anteriori"],
    secondaryMuscles: [],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Schienale aderente, presa neutra o pronata. Range completo controllato.",
    alternatives: ["bench-press-dumbbell", "push-up-standard", "bench-press-flat-barbell"],
    loadable: true,
  },

  // ===========================================================================
  // PATTERN: VERTICAL_PUSH (8 esercizi)
  // ===========================================================================
  {
    id: "military-press-standing-barbell",
    name: "Military Press in piedi (OHP) con bilanciere",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti"],
    secondaryMuscles: ["trapezio", "core", "lombari"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Bilanciere clavicola, gomiti leggermente avanti. Spinta verticale, testa indietro per passare la bar, push dietro al top. Glutei contratti.",
    cautions: ["spalla impingement", "lombare cronico"],
    alternatives: ["seated-shoulder-press-dumbbell", "push-press-barbell", "dumbbell-shoulder-press-standing"],
    loadable: true,
  },
  {
    id: "seated-shoulder-press-dumbbell",
    name: "Shoulder Press seduto con manubri",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti"],
    secondaryMuscles: ["trapezio"],
    equipment: ["dumbbell", "bench"],
    level: "beginner",
    unilateral: false,
    technique: "Schienale 90° o leggermente indietro. Manubri si toccano al top o quasi. ROM ampio.",
    alternatives: ["dumbbell-shoulder-press-standing", "military-press-standing-barbell", "shoulder-press-machine"],
    loadable: true,
  },
  {
    id: "dumbbell-shoulder-press-standing",
    name: "Shoulder Press in piedi con manubri",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti"],
    secondaryMuscles: ["core", "trapezio", "lombari"],
    equipment: ["dumbbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Versione in piedi richiede stabilità core. Manubri partono spalle, spingere verticali. Evitare iperestensione lombare.",
    alternatives: ["seated-shoulder-press-dumbbell", "military-press-standing-barbell", "arnold-press-dumbbell"],
    loadable: true,
  },
  {
    id: "push-press-barbell",
    name: "Push Press con bilanciere",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti", "quadricipiti"],
    secondaryMuscles: ["glutei", "polpaccio", "core"],
    equipment: ["barbell"],
    level: "advanced",
    unilateral: false,
    technique: "Mini-squat, esplosione gambe + push verticale spalle simultanei. Permette carichi maggiori vs strict press.",
    cautions: ["spalla impingement", "ginocchio acuto"],
    alternatives: ["military-press-standing-barbell", "kettlebell-push-press", "dumbbell-shoulder-press-standing"],
    loadable: true,
  },
  {
    id: "kettlebell-push-press",
    name: "Push Press con kettlebell",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti", "quadricipiti"],
    secondaryMuscles: ["core", "glutei"],
    equipment: ["kettlebell"],
    level: "intermediate",
    unilateral: true,
    technique: "Kettlebell in rack position. Mini-dip e drive verticale. Versione monolaterale = challenge stabilità core.",
    alternatives: ["push-press-barbell", "dumbbell-shoulder-press-standing", "military-press-standing-barbell"],
    loadable: true,
  },
  {
    id: "arnold-press-dumbbell",
    name: "Arnold Press con manubri",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi (tutte le porzioni)", "tricipiti"],
    secondaryMuscles: ["trapezio"],
    equipment: ["dumbbell", "bench"],
    level: "intermediate",
    unilateral: false,
    technique: "Partenza supinato davanti al viso. Rotazione + spinta in un movimento fluido fino pronato sopra la testa.",
    alternatives: ["seated-shoulder-press-dumbbell", "dumbbell-shoulder-press-standing", "military-press-standing-barbell"],
    loadable: true,
  },
  {
    id: "pike-push-up",
    name: "Pike Push-up",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti"],
    secondaryMuscles: ["pettorali alti", "core"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: false,
    technique: "Posizione downward dog con anca alta. Discesa testa verso pavimento tra le mani. Progressione verso handstand push-up.",
    alternatives: ["handstand-push-up-bodyweight", "dumbbell-shoulder-press-standing", "push-up-decline"],
    loadable: false,
  },
  {
    id: "handstand-push-up-bodyweight",
    name: "Handstand Push-up",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti", "trapezio"],
    secondaryMuscles: ["core", "stabilizzatori spalla"],
    equipment: ["bodyweight"],
    level: "advanced",
    unilateral: false,
    technique: "Verticale al muro, discesa testa lieve oltre le mani, push verticale. Richiede forza e propriocezione avanzate.",
    cautions: ["spalla acuta", "polso acuto"],
    alternatives: ["pike-push-up", "military-press-standing-barbell", "dumbbell-shoulder-press-standing"],
    loadable: false,
  },
  {
    id: "shoulder-press-machine",
    name: "Shoulder Press alla macchina",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi", "tricipiti"],
    secondaryMuscles: ["trapezio"],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Sedile regolato con manopole all'altezza spalle. Spinta verticale controllata.",
    alternatives: ["seated-shoulder-press-dumbbell", "dumbbell-shoulder-press-standing", "military-press-standing-barbell"],
    loadable: true,
  },

  // ===========================================================================
  // PATTERN: HORIZONTAL_PULL (8 esercizi)
  // ===========================================================================
  {
    id: "barbell-row-bent-over",
    name: "Rematore con bilanciere (bent-over)",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti", "deltoidi posteriori", "core", "lombari"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Hip hinge ~45°, schiena neutra, presa larga prone. Bilanciere allo sterno-ombelico, gomiti vicini al busto.",
    cautions: ["lombare cronico"],
    alternatives: ["dumbbell-row-bent-over", "t-bar-row", "cable-row-seated"],
    loadable: true,
  },
  {
    id: "dumbbell-row-bent-over",
    name: "Rematore con manubri",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti", "deltoidi posteriori"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: true,
    technique: "Una mano + ginocchio su panca. Manubrio neutro, tirare al fianco mantenendo gomito vicino. Squeeze scapolare al top.",
    alternatives: ["barbell-row-bent-over", "cable-row-seated", "inverted-row-bodyweight"],
    loadable: true,
  },
  {
    id: "cable-row-seated",
    name: "Rematore al cavo seduto",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti", "deltoidi posteriori"],
    equipment: ["cable"],
    level: "beginner",
    unilateral: false,
    technique: "Schiena neutra, NO sway lombare. Tirare maniglia all'addome, scapole adduttori al picco.",
    alternatives: ["barbell-row-bent-over", "dumbbell-row-bent-over", "row-machine"],
    loadable: true,
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti", "lombari"],
    equipment: ["barbell"],
    level: "intermediate",
    unilateral: false,
    technique: "Bilanciere ancorato a terra, presa neutra V-bar. Hip hinge + tirata verso lo sterno.",
    cautions: ["lombare cronico"],
    alternatives: ["barbell-row-bent-over", "dumbbell-row-bent-over", "row-machine"],
    loadable: true,
  },
  {
    id: "inverted-row-bodyweight",
    name: "Inverted Row (bodyweight row)",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti", "core"],
    equipment: ["bodyweight", "barbell"],
    level: "beginner",
    unilateral: false,
    technique: "Bilanciere su rack altezza anche, sotto, presa supinata o prona. Tirare petto al bar mantenendo plank.",
    alternatives: ["dumbbell-row-bent-over", "trx-row", "pull-up-bodyweight"],
    loadable: false,
  },
  {
    id: "trx-row",
    name: "TRX Row",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti", "core"],
    equipment: ["trx"],
    level: "beginner",
    unilateral: false,
    technique: "Anelli/maniglie TRX. Difficoltà regolata da angolo del corpo (più orizzontale = più difficile).",
    alternatives: ["inverted-row-bodyweight", "dumbbell-row-bent-over", "cable-row-seated"],
    loadable: false,
  },
  {
    id: "face-pull-cable",
    name: "Face Pull al cavo",
    pattern: "horizontal_pull",
    primaryMuscles: ["deltoidi posteriori", "trapezio medio", "romboidi"],
    secondaryMuscles: ["rotatori esterni"],
    equipment: ["cable"],
    level: "beginner",
    unilateral: false,
    technique: "Cavo altezza viso, corda a doppia maniglia. Tirare verso fronte/orecchie con extra-rotation. Esercizio di salute spalla.",
    alternatives: ["band-pull-apart", "rear-delt-fly-dumbbell", "cable-row-seated"],
    loadable: true,
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    pattern: "horizontal_pull",
    primaryMuscles: ["deltoidi posteriori", "trapezio medio", "romboidi"],
    secondaryMuscles: ["rotatori esterni"],
    equipment: ["band"],
    level: "beginner",
    unilateral: false,
    technique: "Elastico tenuto a braccia tese davanti, tirare orizzontalmente fino petto, scapole pinch.",
    alternatives: ["face-pull-cable", "rear-delt-fly-dumbbell"],
    loadable: false,
  },
  {
    id: "rear-delt-fly-dumbbell",
    name: "Rear Delt Fly con manubri",
    pattern: "horizontal_pull",
    primaryMuscles: ["deltoidi posteriori"],
    secondaryMuscles: ["trapezio medio", "romboidi"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Hip hinge a 45°, manubri leggeri in mano. Sollevare lateralmente con leggera flessione gomito. Range corto.",
    alternatives: ["face-pull-cable", "band-pull-apart"],
    loadable: true,
  },
  {
    id: "row-machine",
    name: "Row alla macchina",
    pattern: "horizontal_pull",
    primaryMuscles: ["dorsali", "romboidi", "trapezio medio"],
    secondaryMuscles: ["bicipiti"],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Petto contro pad. Tirata orizzontale controllata. Buona per beginner: stabilità garantita.",
    alternatives: ["cable-row-seated", "dumbbell-row-bent-over", "barbell-row-bent-over"],
    loadable: true,
  },

  // ===========================================================================
  // PATTERN: VERTICAL_PULL (6 esercizi)
  // ===========================================================================
  {
    id: "pull-up-bodyweight",
    name: "Pull-up (presa prona)",
    pattern: "vertical_pull",
    primaryMuscles: ["dorsali", "bicipiti", "trapezio"],
    secondaryMuscles: ["core", "deltoidi posteriori"],
    equipment: ["bodyweight", "pullup_bar"],
    level: "advanced",
    unilateral: false,
    technique: "Presa prona larghezza poco oltre spalle. Tirata fino mento sopra bar, scapole inizia il movimento. NO swing.",
    alternatives: ["chin-up-bodyweight", "lat-pulldown-machine", "assisted-pull-up-band"],
    loadable: false,
  },
  {
    id: "chin-up-bodyweight",
    name: "Chin-up (presa supinata)",
    pattern: "vertical_pull",
    primaryMuscles: ["dorsali", "bicipiti"],
    secondaryMuscles: ["pettorali", "core"],
    equipment: ["bodyweight", "pullup_bar"],
    level: "intermediate",
    unilateral: false,
    technique: "Presa supinata larghezza spalle. Più contributo bicipiti vs pull-up. Più accessibile per chi inizia.",
    alternatives: ["pull-up-bodyweight", "lat-pulldown-machine", "assisted-pull-up-band"],
    loadable: false,
  },
  {
    id: "assisted-pull-up-band",
    name: "Pull-up assistito con elastico",
    pattern: "vertical_pull",
    primaryMuscles: ["dorsali", "bicipiti", "trapezio"],
    secondaryMuscles: ["core"],
    equipment: ["band", "pullup_bar"],
    level: "beginner",
    unilateral: false,
    technique: "Elastico legato alla bar, piede dentro l'elastico. Assistance graduale per progressione verso pull-up libero.",
    alternatives: ["pull-up-bodyweight", "lat-pulldown-machine", "chin-up-bodyweight"],
    loadable: false,
  },
  {
    id: "lat-pulldown-machine",
    name: "Lat Machine (pulldown)",
    pattern: "vertical_pull",
    primaryMuscles: ["dorsali", "bicipiti"],
    secondaryMuscles: ["trapezio", "deltoidi posteriori"],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Presa larga prona. Tirare bar al petto alto, NON dietro nuca (rischio cervicale). Petto in fuori, no sway.",
    alternatives: ["pull-up-bodyweight", "chin-up-bodyweight", "single-arm-cable-pulldown"],
    loadable: true,
  },
  {
    id: "single-arm-cable-pulldown",
    name: "Pulldown monolaterale al cavo",
    pattern: "vertical_pull",
    primaryMuscles: ["dorsali", "bicipiti"],
    secondaryMuscles: ["core"],
    equipment: ["cable"],
    level: "intermediate",
    unilateral: true,
    technique: "Cavo alto, presa neutra. Tirata verso fianco corrispondente, ROM più ampio per lat stretch.",
    alternatives: ["lat-pulldown-machine", "pull-up-bodyweight", "dumbbell-row-bent-over"],
    loadable: true,
  },
  {
    id: "neutral-grip-pull-up",
    name: "Pull-up presa neutra",
    pattern: "vertical_pull",
    primaryMuscles: ["dorsali", "bicipiti", "brachiale"],
    secondaryMuscles: ["trapezio", "core"],
    equipment: ["bodyweight", "pullup_bar"],
    level: "intermediate",
    unilateral: false,
    technique: "Maniglie parallele neutre. Più gentile su spalle e gomiti vs prona. Buon ponte tra chin-up e pull-up.",
    alternatives: ["pull-up-bodyweight", "chin-up-bodyweight", "lat-pulldown-machine"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: CARRY (4 esercizi)
  // ===========================================================================
  {
    id: "farmers-walk-dumbbell",
    name: "Farmer's Walk con manubri",
    pattern: "carry",
    primaryMuscles: ["trapezio", "core", "avambracci"],
    secondaryMuscles: ["glutei", "quadricipiti", "stabilizzatori"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Carichi pesanti per mano, busto eretto, scapole abbassate. Camminata 20-40m, respirazione regolare.",
    alternatives: ["farmers-walk-kettlebell", "suitcase-carry-kettlebell", "overhead-carry-dumbbell"],
    loadable: true,
  },
  {
    id: "farmers-walk-kettlebell",
    name: "Farmer's Walk con kettlebell",
    pattern: "carry",
    primaryMuscles: ["trapezio", "core", "avambracci"],
    secondaryMuscles: ["glutei", "quadricipiti"],
    equipment: ["kettlebell"],
    level: "beginner",
    unilateral: false,
    technique: "Identica a farmer's walk con manubri. KB oscilla meno se distanza percorsa lunga.",
    alternatives: ["farmers-walk-dumbbell", "suitcase-carry-kettlebell", "rack-carry-kettlebell"],
    loadable: true,
  },
  {
    id: "suitcase-carry-kettlebell",
    name: "Suitcase Carry monolaterale",
    pattern: "carry",
    primaryMuscles: ["core (anti-laterale)", "obliqui", "trapezio"],
    secondaryMuscles: ["avambracci", "glutei"],
    equipment: ["kettlebell"],
    level: "beginner",
    unilateral: true,
    technique: "Kettlebell pesante in una sola mano. Anti-laterale flexion: NO inclinazione laterale del busto. Camminare 20-30m.",
    alternatives: ["farmers-walk-dumbbell", "side-plank-bodyweight", "pallof-press-cable"],
    loadable: true,
  },
  {
    id: "overhead-carry-dumbbell",
    name: "Overhead Carry con manubrio",
    pattern: "carry",
    primaryMuscles: ["deltoidi", "core", "trapezio"],
    secondaryMuscles: ["stabilizzatori spalla"],
    equipment: ["dumbbell"],
    level: "intermediate",
    unilateral: true,
    technique: "Manubrio sopra la testa braccio teso, gomito locked. Camminare mantenendo asse spalla-gomito-polso.",
    cautions: ["spalla impingement"],
    alternatives: ["farmers-walk-dumbbell", "rack-carry-kettlebell", "suitcase-carry-kettlebell"],
    loadable: true,
  },
  {
    id: "rack-carry-kettlebell",
    name: "Rack Carry con kettlebell",
    pattern: "carry",
    primaryMuscles: ["core", "trapezio"],
    secondaryMuscles: ["bicipiti", "stabilizzatori"],
    equipment: ["kettlebell"],
    level: "intermediate",
    unilateral: true,
    technique: "KB in rack position (gomito basso, polso neutro). Camminare 20-30m. Variante anti-rotazione.",
    alternatives: ["farmers-walk-kettlebell", "suitcase-carry-kettlebell", "overhead-carry-dumbbell"],
    loadable: true,
  },

  // ===========================================================================
  // PATTERN: CORE_ANTIEXT (anti-extension) - 5 esercizi
  // ===========================================================================
  {
    id: "plank-front-bodyweight",
    name: "Plank frontale",
    pattern: "core_antiext",
    primaryMuscles: ["retto addominale", "trasverso"],
    secondaryMuscles: ["glutei", "deltoidi"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Avambracci a terra, corpo in linea retta tallone-anca-spalla. Glutei contratti, NO anche cadenti. Mantenere 30-60s.",
    alternatives: ["plank-knees", "rkc-plank", "dead-bug-bodyweight"],
    loadable: false,
  },
  {
    id: "plank-knees",
    name: "Plank sulle ginocchia",
    pattern: "core_antiext",
    primaryMuscles: ["retto addominale", "trasverso"],
    secondaryMuscles: ["deltoidi"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Versione regression. Linea retta ginocchio-anca-spalla. 20-40s.",
    alternatives: ["plank-front-bodyweight", "dead-bug-bodyweight"],
    loadable: false,
  },
  {
    id: "rkc-plank",
    name: "RKC Plank (intensified)",
    pattern: "core_antiext",
    primaryMuscles: ["retto addominale", "trasverso", "obliqui"],
    secondaryMuscles: ["glutei", "quadricipiti", "deltoidi"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: false,
    technique: "Plank classico + contrazione massimale glutei + quadricipiti + addome. Tenuta 10-30s, intensità massima.",
    alternatives: ["plank-front-bodyweight", "hollow-body-hold", "dead-bug-bodyweight"],
    loadable: false,
  },
  {
    id: "dead-bug-bodyweight",
    name: "Dead Bug",
    pattern: "core_antiext",
    primaryMuscles: ["retto addominale", "trasverso"],
    secondaryMuscles: ["flessori anca"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Schiena a terra, braccia + gambe verso il soffitto. Estendere braccio + gamba opposti senza staccare lombare dal pavimento.",
    alternatives: ["bird-dog-bodyweight", "plank-front-bodyweight", "hollow-body-hold"],
    loadable: false,
  },
  {
    id: "bird-dog-bodyweight",
    name: "Bird Dog",
    pattern: "core_antiext",
    primaryMuscles: ["erettori spinali", "glutei", "trasverso"],
    secondaryMuscles: ["deltoidi posteriori", "core anti-rotazione"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Quadrupedia, braccio dx + gamba sx estesi paralleli al pavimento, bacino stabile (no rotazioni). Tenuta 2-3s, alternare.",
    alternatives: ["dead-bug-bodyweight", "plank-front-bodyweight", "single-leg-balance"],
    loadable: false,
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    pattern: "core_antiext",
    primaryMuscles: ["retto addominale", "trasverso"],
    secondaryMuscles: ["flessori anca", "deltoidi"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: false,
    technique: "Schiena schiacciata a terra, braccia e gambe estese sopra/davanti al pavimento (15-20°). Tenuta 20-45s.",
    alternatives: ["dead-bug-bodyweight", "plank-front-bodyweight", "rkc-plank"],
    loadable: false,
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    pattern: "core_antiext",
    primaryMuscles: ["retto addominale", "trasverso", "dorsali"],
    secondaryMuscles: ["deltoidi", "tricipiti"],
    equipment: ["bodyweight"],
    level: "advanced",
    unilateral: false,
    technique: "Da ginocchia, ruota in avanti mantenendo lombare neutra (NO inarcamento). Tornare contraendo addome.",
    cautions: ["lombare cronico"],
    alternatives: ["plank-front-bodyweight", "hollow-body-hold", "dead-bug-bodyweight"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: CORE_ANTIROT (anti-rotation) - 5 esercizi
  // ===========================================================================
  {
    id: "pallof-press-cable",
    name: "Pallof Press al cavo",
    pattern: "core_antirot",
    primaryMuscles: ["obliqui", "trasverso"],
    secondaryMuscles: ["deltoidi", "glutei"],
    equipment: ["cable"],
    level: "beginner",
    unilateral: true,
    technique: "Cavo altezza petto perpendicolare al corpo. Estendere braccia avanti resistendo a rotazione. Tenere 2-5s, ripetere.",
    alternatives: ["pallof-press-band", "side-plank-bodyweight", "wood-chop-cable"],
    loadable: true,
  },
  {
    id: "pallof-press-band",
    name: "Pallof Press con elastico",
    pattern: "core_antirot",
    primaryMuscles: ["obliqui", "trasverso"],
    secondaryMuscles: ["deltoidi", "glutei"],
    equipment: ["band"],
    level: "beginner",
    unilateral: true,
    technique: "Identica a versione cavo. Elastico ancorato a punto fisso. Versione home-gym.",
    alternatives: ["pallof-press-cable", "side-plank-bodyweight", "wood-chop-cable"],
    loadable: false,
  },
  {
    id: "wood-chop-cable",
    name: "Cable Wood Chop",
    pattern: "core_antirot",
    primaryMuscles: ["obliqui", "addominali"],
    secondaryMuscles: ["deltoidi", "glutei"],
    equipment: ["cable"],
    level: "intermediate",
    unilateral: true,
    technique: "Cavo alto, tirare diagonalmente verso anca opposta. Movimento generato da rotazione anca + core, NO solo braccia.",
    alternatives: ["pallof-press-cable", "russian-twist-bodyweight"],
    loadable: true,
  },
  {
    id: "side-plank-bodyweight",
    name: "Side Plank",
    pattern: "core_antirot",
    primaryMuscles: ["obliqui", "quadrato lombi"],
    secondaryMuscles: ["glutei", "deltoidi"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Avambraccio a terra, corpo in linea, anca sollevata. NO bacino caduto. 30-60s per lato.",
    alternatives: ["copenhagen-plank", "pallof-press-cable", "side-plank-knees"],
    loadable: false,
  },
  {
    id: "side-plank-knees",
    name: "Side Plank sulle ginocchia",
    pattern: "core_antirot",
    primaryMuscles: ["obliqui"],
    secondaryMuscles: ["deltoidi"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Versione regression. Avambraccio + ginocchio a terra. Anca sollevata, linea ginocchio-spalla.",
    alternatives: ["side-plank-bodyweight", "pallof-press-band"],
    loadable: false,
  },
  {
    id: "russian-twist-bodyweight",
    name: "Russian Twist",
    pattern: "core_antirot",
    primaryMuscles: ["obliqui"],
    secondaryMuscles: ["addominali", "flessori anca"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "Seduto, ginocchia piegate, busto inclinato 45°. Rotazione controllata lato a lato. Aggiungere peso per progressione.",
    cautions: ["lombare cronico"],
    alternatives: ["wood-chop-cable", "side-plank-bodyweight", "pallof-press-cable"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: PLYOMETRIC (5 esercizi)
  // ===========================================================================
  {
    id: "box-jump",
    name: "Box Jump",
    pattern: "plyometric",
    primaryMuscles: ["quadricipiti", "glutei", "polpaccio"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight", "box"],
    level: "intermediate",
    unilateral: false,
    technique: "Mini-squat + esplosione verticale, atterraggio morbido sulla box (NO gambe rigide). Step-down per scendere, NO salto giù.",
    cautions: ["ginocchio acuto", "polpaccio strain recente"],
    alternatives: ["broad-jump", "jump-squat-bodyweight", "depth-jump"],
    loadable: false,
  },
  {
    id: "broad-jump",
    name: "Broad Jump (salto in lungo)",
    pattern: "plyometric",
    primaryMuscles: ["quadricipiti", "glutei", "polpaccio"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: false,
    technique: "Counter-movement + esplosione orizzontale. Atterraggio in mini-squat con assorbimento. Reset prima di ripetere.",
    cautions: ["polpaccio recente"],
    alternatives: ["box-jump", "jump-squat-bodyweight", "bounding-bodyweight"],
    loadable: false,
  },
  {
    id: "depth-jump",
    name: "Depth Jump",
    pattern: "plyometric",
    primaryMuscles: ["quadricipiti", "glutei", "polpaccio"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["bodyweight", "box"],
    level: "advanced",
    unilateral: false,
    technique: "Step-down da box 30-50cm, atterraggio + esplosione verticale immediata (reactive strength). Min ground contact time.",
    cautions: ["ginocchio acuto", "polpaccio strain", "tendine achille"],
    alternatives: ["box-jump", "broad-jump", "bounding-bodyweight"],
    loadable: false,
  },
  {
    id: "bounding-bodyweight",
    name: "Bounding (balzi alternati)",
    pattern: "plyometric",
    primaryMuscles: ["quadricipiti", "glutei", "polpaccio"],
    secondaryMuscles: ["femorali", "core"],
    equipment: ["bodyweight"],
    level: "advanced",
    unilateral: true,
    technique: "Balzi orizzontali alternati gamba a gamba, massima estensione anca + ginocchio. Ottimo per power runner.",
    cautions: ["polpaccio strain", "ginocchio acuto"],
    alternatives: ["broad-jump", "box-jump", "skipping-bodyweight"],
    loadable: false,
  },
  {
    id: "skipping-bodyweight",
    name: "A-Skip / B-Skip drill",
    pattern: "plyometric",
    primaryMuscles: ["polpaccio", "quadricipiti", "flessori anca"],
    secondaryMuscles: ["glutei", "core"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Skip alto con ginocchio a 90° (A-skip) o estensione gamba bassa (B-skip). Drill di running form + warm-up.",
    alternatives: ["bounding-bodyweight", "jump-squat-bodyweight"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: SPORT-SPECIFIC CALCIO (4 esercizi)
  // ===========================================================================
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    pattern: "hinge",
    primaryMuscles: ["femorali (eccentrico)"],
    secondaryMuscles: ["glutei", "core"],
    equipment: ["bodyweight"],
    level: "advanced",
    unilateral: false,
    technique: "Inginocchiati, caviglie bloccate (partner o panca apposita). Discesa controllata in avanti il più possibile, push-up al ritorno se necessario. 3×5-10 eccentriche.",
    cautions: ["femorale strain recente"],
    alternatives: ["deadlift-romanian-barbell", "single-leg-rdl-dumbbell", "glute-bridge-bodyweight"],
    loadable: false,
  },
  {
    id: "copenhagen-plank",
    name: "Copenhagen Plank",
    pattern: "core_antirot",
    primaryMuscles: ["adduttori", "obliqui"],
    secondaryMuscles: ["glutei", "core"],
    equipment: ["bodyweight", "bench"],
    level: "advanced",
    unilateral: true,
    technique: "Side plank con gamba alta su panca (caviglia o ginocchio appoggiato). Anca sollevata. Prevenzione strain adduttori (specifico calcio).",
    cautions: ["adduttore strain"],
    alternatives: ["side-plank-bodyweight", "side-plank-knees"],
    loadable: false,
  },
  {
    id: "single-leg-balance-bodyweight",
    name: "Single-Leg Balance (propriocezione)",
    pattern: "isometric",
    primaryMuscles: ["stabilizzatori caviglia", "glutei medi"],
    secondaryMuscles: ["core", "quadricipiti"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: true,
    technique: "Stand monopodalico 30-60s. Progressione: occhi chiusi, superficie instabile (cuscino), gesti dinamici (passare oggetto).",
    alternatives: ["single-leg-glute-bridge", "bulgarian-split-squat-bodyweight"],
    loadable: false,
  },
  {
    id: "lateral-bound-bodyweight",
    name: "Lateral Bound (skater jump)",
    pattern: "plyometric",
    primaryMuscles: ["quadricipiti", "glutei", "adduttori"],
    secondaryMuscles: ["polpaccio", "core"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: true,
    technique: "Salto laterale ampio gamba a gamba (skater pattern). Atterraggio controllato + tenuta 1s prima del rebound. Cambio direzione esplosivo.",
    cautions: ["ginocchio acuto", "adduttore strain"],
    alternatives: ["bounding-bodyweight", "broad-jump", "lateral-lunge-dumbbell"],
    loadable: false,
  },

  // ===========================================================================
  // PATTERN: SUPPLEMENTARI ACCESSORI (calf, biceps, triceps, lat work)
  // ===========================================================================
  {
    id: "calf-raise-standing",
    name: "Calf Raise in piedi",
    pattern: "isometric",
    primaryMuscles: ["polpaccio (gastrocnemio)"],
    secondaryMuscles: ["soleo"],
    equipment: ["bodyweight"],
    level: "beginner",
    unilateral: false,
    technique: "In piedi, sollevarsi su punta dei piedi a ginocchia tese (mira gastrocnemio). 3×15-20 rep, controllato.",
    alternatives: ["calf-raise-seated", "single-leg-calf-raise", "calf-raise-machine"],
    loadable: false,
  },
  {
    id: "calf-raise-seated",
    name: "Calf Raise seduto",
    pattern: "isometric",
    primaryMuscles: ["soleo"],
    secondaryMuscles: ["gastrocnemio"],
    equipment: ["dumbbell", "bench"],
    level: "beginner",
    unilateral: false,
    technique: "Seduto, manubri sulle cosce. A ginocchia piegate mira soleo (80% volume polpaccio). Critical per runner injury prevention.",
    alternatives: ["calf-raise-standing", "calf-raise-machine", "single-leg-calf-raise"],
    loadable: true,
  },
  {
    id: "single-leg-calf-raise",
    name: "Single-Leg Calf Raise",
    pattern: "isometric",
    primaryMuscles: ["polpaccio"],
    secondaryMuscles: ["stabilizzatori caviglia"],
    equipment: ["bodyweight"],
    level: "intermediate",
    unilateral: true,
    technique: "Una gamba sola, su gradino per ROM completo (eccentrico Alfredson per tendinopatia). 3×15 rep eccentriche lente.",
    alternatives: ["calf-raise-standing", "calf-raise-seated"],
    loadable: false,
  },
  {
    id: "calf-raise-machine",
    name: "Calf Raise alla macchina",
    pattern: "isometric",
    primaryMuscles: ["polpaccio"],
    secondaryMuscles: [],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Standing o seated calf machine. Pieno ROM (top + bottom). Buon carico progressivo.",
    alternatives: ["calf-raise-standing", "calf-raise-seated"],
    loadable: true,
  },
  {
    id: "bicep-curl-dumbbell",
    name: "Bicep Curl con manubri",
    pattern: "vertical_pull",
    primaryMuscles: ["bicipiti"],
    secondaryMuscles: ["brachiale", "avambracci"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Gomiti fissi al busto, supinazione progressiva durante salita. NO swing del busto.",
    alternatives: ["hammer-curl-dumbbell", "bicep-curl-barbell", "chin-up-bodyweight"],
    loadable: true,
  },
  {
    id: "hammer-curl-dumbbell",
    name: "Hammer Curl con manubri",
    pattern: "vertical_pull",
    primaryMuscles: ["brachiale", "bicipiti"],
    secondaryMuscles: ["avambracci"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Presa neutra (palmo verso il corpo). Più stimolo brachiale. Forza presa.",
    alternatives: ["bicep-curl-dumbbell", "bicep-curl-barbell"],
    loadable: true,
  },
  {
    id: "bicep-curl-barbell",
    name: "Bicep Curl con bilanciere",
    pattern: "vertical_pull",
    primaryMuscles: ["bicipiti"],
    secondaryMuscles: ["brachiale", "avambracci"],
    equipment: ["barbell"],
    level: "beginner",
    unilateral: false,
    technique: "Bilanciere presa supinata larghezza spalle. Gomiti fissi, sollevamento controllato. Carichi più alti vs manubri.",
    alternatives: ["bicep-curl-dumbbell", "hammer-curl-dumbbell"],
    loadable: true,
  },
  {
    id: "tricep-extension-dumbbell",
    name: "Tricep Extension con manubrio (overhead)",
    pattern: "vertical_push",
    primaryMuscles: ["tricipiti"],
    secondaryMuscles: ["deltoidi posteriori"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Manubrio sopra la testa a due mani, gomiti fissi vicini alle orecchie. Discesa controllata dietro la testa.",
    cautions: ["spalla impingement", "gomito"],
    alternatives: ["tricep-pushdown-cable", "bench-dips", "dips-parallel-bars"],
    loadable: true,
  },
  {
    id: "tricep-pushdown-cable",
    name: "Tricep Pushdown al cavo",
    pattern: "vertical_push",
    primaryMuscles: ["tricipiti"],
    secondaryMuscles: [],
    equipment: ["cable"],
    level: "beginner",
    unilateral: false,
    technique: "Cavo alto con corda o sbarra dritta. Gomiti fissi al busto, estensione completa al fondo.",
    alternatives: ["tricep-extension-dumbbell", "bench-dips", "dips-parallel-bars"],
    loadable: true,
  },
  {
    id: "lateral-raise-dumbbell",
    name: "Alzate laterali con manubri",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi laterali"],
    secondaryMuscles: ["trapezio", "sovraspinato"],
    equipment: ["dumbbell"],
    level: "beginner",
    unilateral: false,
    technique: "Manubri leggeri lungo i fianchi. Sollevare lateralmente fino spalla, leggera flessione gomito. NO scendere sotto il livello.",
    alternatives: ["lateral-raise-cable", "shoulder-press-machine"],
    loadable: true,
  },
  {
    id: "lateral-raise-cable",
    name: "Alzate laterali al cavo",
    pattern: "vertical_push",
    primaryMuscles: ["deltoidi laterali"],
    secondaryMuscles: ["trapezio"],
    equipment: ["cable"],
    level: "intermediate",
    unilateral: true,
    technique: "Cavo basso, maniglia singola. Tensione costante in tutto il ROM (vantaggio vs manubri). Range corto controllato.",
    alternatives: ["lateral-raise-dumbbell"],
    loadable: true,
  },
  {
    id: "leg-extension-machine",
    name: "Leg Extension alla macchina",
    pattern: "isometric",
    primaryMuscles: ["quadricipiti"],
    secondaryMuscles: [],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Macchina con pad sulle tibie. Estensione ginocchio completa, NO swing. Isolamento quadricipiti.",
    cautions: ["ginocchio acuto"],
    alternatives: ["bodyweight-squat", "leg-press-machine", "bulgarian-split-squat-dumbbell"],
    loadable: true,
  },
  {
    id: "leg-curl-machine",
    name: "Leg Curl alla macchina",
    pattern: "hinge",
    primaryMuscles: ["femorali"],
    secondaryMuscles: ["polpaccio"],
    equipment: ["machine"],
    level: "beginner",
    unilateral: false,
    technique: "Prono o seduto a seconda macchina. Flessione ginocchio controllata, NO arching lombare in versione prona.",
    alternatives: ["nordic-hamstring-curl", "deadlift-romanian-barbell", "single-leg-rdl-dumbbell"],
    loadable: true,
  },
  {
    id: "single-leg-box-squat",
    name: "Single-Leg Box Squat",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei"],
    secondaryMuscles: ["core", "stabilizzatori"],
    equipment: ["bodyweight", "box"],
    level: "intermediate",
    unilateral: true,
    technique: "Squat su una gamba sedendosi su box altezza ginocchio. Versione progression verso pistol squat.",
    alternatives: ["pistol-squat-bodyweight", "bulgarian-split-squat-bodyweight", "step-up-dumbbell"],
    loadable: false,
  },
  {
    id: "zercher-squat-barbell",
    name: "Zercher Squat",
    pattern: "squat",
    primaryMuscles: ["quadricipiti", "glutei", "core"],
    secondaryMuscles: ["bicipiti (isometrico)", "lombari"],
    equipment: ["barbell"],
    level: "advanced",
    unilateral: false,
    technique: "Bilanciere nell'incavo dei gomiti. Forza il busto verticale, anti-flessione core estremo. Variante avanzata.",
    cautions: ["gomito acuto"],
    alternatives: ["front-squat-barbell", "goblet-squat-kettlebell", "back-squat-barbell"],
    loadable: true,
  },
];

/**
 * Lookup O(1) per esercizio dall'id.
 * Iniettato nei prompt LLM via contract con Schema Specialist (vedi §5.1).
 */
export const EXERCISES_BY_ID: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map(e => [e.id, e])
);

/**
 * Lista completa degli ID validi (per validazione runtime + injection prompt).
 */
export const EXERCISE_IDS: ReadonlySet<string> = new Set(EXERCISES.map(e => e.id));
